---
name: Windows / MS Visual Studio / CPU tests

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
      - 'release*'
      - 'ms-visual-studio'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'CHANGES'
      - 'COPYING'
      - 'CREDITS'
      - 'LICENSE'
      - 'README.*'
      - 'tools/docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: cmd /C call {0}

jobs:
  msvc_test_matrix:
    name: LLVM ${{ matrix.llvm_version }} - ${{ matrix.config }} - shared libs:${{ matrix.shared_libs }}
    runs-on: [windows-2022]
    strategy:
      fail-fast: false
      matrix:
        llvm_version: [18, 19]
        shared_libs: [ON, OFF]
        config: [cpu]

    steps:
      - name: Checkout PoCL
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Source MSVC tools. This is a known way to have the PoCL configuration
      # step to pick up MSVC compiler (cl.exe) instead of MinGW's gcc.
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@fb19abb8a41b3cf0340f5d1be17d420309232be6
        with:
          arch: x64

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: pocl-deps
          init-shell: cmd.exe
          create-args: >-
            llvmdev=${{ matrix.llvm_version }}
            clangdev=${{ matrix.llvm_version }}
            ninja

      - name: Load Env vars
        id: load-env
        run: |
          cat ${{ github.workspace }}/.github/variables.txt >> $GITHUB_ENV

      - name: Check llvm
        run: |
          where llvm-config.exe
          where clang-cl.exe

      # Keep this aligned with the Windows/MSVC build instructions
      # (docs/sphinx/source/windows.rst). This configuration step is
      # intended to pick up MSVC as the compiler, but if the
      # environment is not set properly, it might pick up MinGW-gcc instead.
      - name: Configure PoCL
        run: |
          set "CC=clang-cl.exe"
          set "CXX=clang-cl.exe"
          cmake -S . -B build-pocl
              -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\install-pocl
              -DENABLE_ICD=0
              -DENABLE_LLVM=1
              -DENABLE_LOADABLE_DRIVERS=OFF
              -DSTATIC_LLVM=ON
              -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL
              -DBUILD_SHARED_LIBS=${{ matrix.shared_libs }}
              -G "Ninja"

      - name: Build PoCL
        run: cmake --build build-pocl

      - name: Run Tests
        env:
          POCL_CACHE_DIR: "${{ runner.temp }}/GH_POCL_CACHE"
        timeout-minutes: 120
        run: |
          if (Test-Path -path ${{ env.POCL_CACHE_DIR }}) {
            rm -r ${{ env.POCL_CACHE_DIR }}
          }
          mkdir ${{ env.POCL_CACHE_DIR }}
          cd ${{ github.workspace }}\build-pocl
          & ${{ github.workspace }}\tools\scripts\run_cpu_tests.ps1 $CTEST_FLAGS -j$Env:NUMBER_OF_PROCESSORS
